config/routes.rb
Rails.application.routes.draw do
  get 'restaurants', to: 'restaurants#index', as: :restaurants

  # get 'restaurants/new', to: 'restaurants#new', as: :new_restaurant
  # post 'restaurants', to: 'restaurants#create'

  # get 'restaurants/:id', to: 'restaurants#show', as: :restaurant

  # get "restaurants/:restaurant_id/reviews/new", to: 'reviews#new'
  # post 'restaurants/:restaurant_id/reviews', to 'reviews#new'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, numericality: { greater_than_or_equal_to: 0}
  validates :rating, numericality: { less_than_or_equal_to: 5}
  validates :restaurant, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  # A visitor can see the list of all restaurants.
  def index
    @restaurants = Restaurant.all
  end

  # She/He can see the details of a restaurant, with all the reviews related to the restaurant.
  def show
    @restaurants = Restaurant.find(params[:id])
  end

  # She/He can add a new restaurant, and be redirected to the show view of that new restaurant.
  def new
    @restaurant = Restaurant.new
  end

  def create

  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>

  <%= javascript_include_tag "application" %>
  <%= javascript_pack_tag "application" %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>All restaurant on one glanze</h1>

<ul>
  <% @restaurants.each do |restaurant|  %>
    <li> <%= link_to restaurant.name, restaurants_path(restaurant)%></li>
  <% end %>
</ul>